---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    groups:
      - "${MOLECULE_LOGID_VERSION:-v0.3.3}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
  inventory:
    group_vars:
      v0.2.4:
        logid_version: v0.2.4
        logid_cmake_cmd: "cmake .."
      v0.3.0:
        logid_version: v0.3.0
      v0.3.1:
        logid_version: v0.3.1
      v0.3.2:
        logid_version: v0.3.2
      v0.3.3:
        logid_version: v0.3.3
