---
- name: Converge
  hosts: all
  tasks:
    - name: Get info about services
      ansible.builtin.service_facts:
      register: services

    - name: Assert that logid is running
      ansible.builtin.assert:
        that:
          - services['logid.service']['state'] == running
