name: CI
on: [push]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: python3 -m pip install --user ansible-lint

      - name: Lint
        run: ansible-lint .

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian12
#          - fedora38
#          - rockylinux8
#          - rockylinux9
          - ubuntu2204
        logid_version:
          - v0.2.4
          - v0.3.0
          - v0.3.1
          - v0.3.2
          - v0.3.3

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: python3 -m pip install --user ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_LOGID_VESRION: ${{ matrix.logid_version }}
